//go:build ignore

// Command gensemconv walks the vendored OTel semantic-conventions model YAML
// snapshot and emits rules/semconv_data.go.
//
// Usage (from the repo root):
//
//	go run ./tools/gensemconv/main.go
//
// When to re-run: whenever tools/gensemconv/model/ is updated to a new
// semantic-conventions release tag. After running, review the diff and commit
// both the updated model/ snapshot and the regenerated rules/semconv_data.go.
//
// Vendored snapshot scope: tools/gensemconv/model/ holds only the YAML files
// that contain a `type: metric` group (plus README.md and version.properties
// for provenance) — the attribute-registry, span, event, and entity files the
// generator never reads are pruned to keep the snapshot lean. When re-vendoring
// a new release, copy the upstream model/ subtree, run this generator to confirm
// the metric/namespace counts, then drop every file with no `type: metric` group.
//
// Source: tools/gensemconv/model/ (open-telemetry/semantic-conventions v1.41.1,
// vendored from https://github.com/open-telemetry/semantic-conventions).
// Network is NOT accessed at build time; only the local vendored files are read.
package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// semconvFile represents the top-level structure of a semantic-conventions
// model YAML file.
type semconvFile struct {
	Groups []group `yaml:"groups"`
}

// group represents a single entry in the groups[] array.
type group struct {
	Type       string `yaml:"type"`
	MetricName string `yaml:"metric_name"`
}

func main() {
	modelDir := "tools/gensemconv/model"
	outPath := "rules/semconv_data.go"

	metricNames := make(map[string]bool)

	err := filepath.WalkDir(modelDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".yaml") {
			return nil
		}

		data, err := os.ReadFile(path)
		if err != nil {
			return fmt.Errorf("reading %s: %w", path, err)
		}

		var f semconvFile
		if err := yaml.Unmarshal(data, &f); err != nil {
			// Some YAML files may have anchors or other features; skip on error.
			fmt.Fprintf(os.Stderr, "gensemconv: skipping %s: %v\n", path, err)
			return nil
		}

		for _, g := range f.Groups {
			if g.Type == "metric" && g.MetricName != "" {
				metricNames[g.MetricName] = true
			}
		}
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "gensemconv: walk error: %v\n", err)
		os.Exit(1)
	}

	// Derive namespaces: root segment (text before first '.') of each metric name.
	namespaces := make(map[string]bool)
	for name := range metricNames {
		dot := strings.Index(name, ".")
		if dot > 0 {
			namespaces[name[:dot]] = true
		} else {
			namespaces[name] = true
		}
	}

	// Sort for deterministic output.
	sortedNames := sortedKeys(metricNames)
	sortedNamespaces := sortedKeys(namespaces)

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/gensemconv/main.go — DO NOT EDIT.\n")
	sb.WriteString("//\n")
	sb.WriteString("// To regenerate, run from the repo root:\n")
	sb.WriteString("//\n")
	sb.WriteString("//\tgo run ./tools/gensemconv/main.go\n")
	sb.WriteString("//\n")
	sb.WriteString("// Source: tools/gensemconv/model/ (open-telemetry/semantic-conventions v1.41.1,\n")
	sb.WriteString("// vendored from https://github.com/open-telemetry/semantic-conventions).\n")
	sb.WriteString("// Network is NOT accessed at build time.\n")
	sb.WriteString("\n")
	sb.WriteString("package rules\n")
	sb.WriteString("\n")

	// semconvMetricNames
	sb.WriteString("// semconvMetricNames is the set of all metric names defined in the\n")
	sb.WriteString("// OTel semantic conventions (stable AND development stability levels),\n")
	sb.WriteString("// extracted from the vendored model YAML snapshot.\n")
	sb.WriteString("var semconvMetricNames = map[string]bool{\n")
	for _, name := range sortedNames {
		fmt.Fprintf(&sb, "\t%q: true,\n", name)
	}
	sb.WriteString("}\n\n")

	// semconvNamespaces
	sb.WriteString("// semconvNamespaces is the set of root segments (text before the first '.')\n")
	sb.WriteString("// of all semconv metric names. Used to detect metrics that belong to a\n")
	sb.WriteString("// known semconv namespace.\n")
	sb.WriteString("var semconvNamespaces = map[string]bool{\n")
	for _, ns := range sortedNamespaces {
		fmt.Fprintf(&sb, "\t%q: true,\n", ns)
	}
	sb.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(sb.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gensemconv: cannot write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("gensemconv: wrote %s (%d metric names, %d namespaces)\n",
		outPath, len(metricNames), len(namespaces))
}

func sortedKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
