//go:build ignore

// Command genucum parses the vendored UCUM essence XML and emits rules/ucum_data.go.
//
// Usage (from the repo root):
//
//	go run ./tools/genucum/main.go
//
// When to re-run: whenever tools/genucum/ucum-essence.xml is updated (UCUM
// releases roughly yearly). After running, review the diff and commit both
// the updated XML and the regenerated rules/ucum_data.go.
//
// Source file: tools/genucum/ucum-essence.xml (UCUM v2.2, vendored from
// https://raw.githubusercontent.com/ucum-org/ucum/main/ucum-essence.xml).
// Network is NOT accessed at build time; only the local vendored file is read.
package main

import (
	"encoding/xml"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
)

// ucumRoot is the top-level element of the UCUM essence XML.
type ucumRoot struct {
	XMLName  xml.Name    `xml:"root"`
	Prefixes []prefix    `xml:"prefix"`
	BaseUnits []baseUnit `xml:"base-unit"`
	Units    []unit      `xml:"unit"`
}

type prefix struct {
	Code string `xml:"Code,attr"`
}

type baseUnit struct {
	Code string `xml:"Code,attr"`
}

type unit struct {
	Code string `xml:"Code,attr"`
}

func main() {
	// Locate the XML file relative to this source file's directory.
	// When invoked as "go run ./tools/genucum/main.go" from the repo root,
	// the working directory is the repo root.
	xmlPath := "tools/genucum/ucum-essence.xml"
	outPath := "rules/ucum_data.go"

	f, err := os.Open(xmlPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genucum: cannot open %s: %v\n", xmlPath, err)
		os.Exit(1)
	}
	defer f.Close()

	var root ucumRoot
	dec := xml.NewDecoder(f)
	// The file declares encoding="ascii"; ASCII is a subset of UTF-8 so we
	// can safely read it as UTF-8. Provide a no-op CharsetReader so the
	// standard library does not reject the declaration.
	dec.CharsetReader = func(_ string, r io.Reader) (io.Reader, error) {
		return r, nil
	}
	if err := dec.Decode(&root); err != nil {
		fmt.Fprintf(os.Stderr, "genucum: cannot parse %s: %v\n", xmlPath, err)
		os.Exit(1)
	}

	// Build atom set: base-unit codes + unit codes + manual unity "1".
	atomSet := make(map[string]bool)
	atomSet["1"] = true // UCUM implicit unity
	for _, bu := range root.BaseUnits {
		atomSet[bu.Code] = true
	}
	for _, u := range root.Units {
		atomSet[u.Code] = true
	}

	// Build prefix set from the XML.
	prefixSet := make(map[string]bool)
	for _, p := range root.Prefixes {
		prefixSet[p.Code] = true
	}

	// Collect and sort for deterministic output.
	atoms := sortedKeys(atomSet)
	prefixes := sortedKeys(prefixSet)

	// verboseToUCUM maps English verbose words (lowercase) to UCUM codes.
	// Seeded from OTel's wordToUCUM table; NOT derived from the XML.
	verboseEntries := []struct{ key, val string }{
		{"seconds", "s"},
		{"milliseconds", "ms"},
		{"microseconds", "us"},
		{"nanoseconds", "ns"},
		{"minutes", "min"},
		{"hours", "h"},
		{"days", "d"},
		{"bytes", "By"},
		{"kibibytes", "KiBy"},
		{"mebibytes", "MiBy"},
		{"gibibytes", "GiBy"},
		{"kilobytes", "KBy"},
		{"megabytes", "MBy"},
		{"gigabytes", "GBy"},
		{"meters", "m"},
		{"volts", "V"},
		{"amperes", "A"},
		{"joules", "J"},
		{"watts", "W"},
		{"grams", "g"},
		{"celsius", "Cel"},
		{"hertz", "Hz"},
		{"ratio", "1"},
		{"percent", "%"},
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by tools/genucum/main.go — DO NOT EDIT.\n")
	sb.WriteString("//\n")
	sb.WriteString("// To regenerate, run from the repo root:\n")
	sb.WriteString("//\n")
	sb.WriteString("//\tgo run ./tools/genucum/main.go\n")
	sb.WriteString("//\n")
	sb.WriteString("// Source: tools/genucum/ucum-essence.xml (UCUM v2.2).\n")
	sb.WriteString("// Network is NOT accessed at build time.\n")
	sb.WriteString("\n")
	sb.WriteString("package rules\n")
	sb.WriteString("\n")

	// ucumAtoms
	sb.WriteString("// ucumAtoms is the set of all UCUM case-sensitive atom codes\n")
	sb.WriteString("// (base units + units) extracted from ucum-essence.xml, plus\n")
	sb.WriteString("// the implicit unity \"1\".\n")
	sb.WriteString("var ucumAtoms = map[string]bool{\n")
	for _, a := range atoms {
		fmt.Fprintf(&sb, "\t%q: true,\n", a)
	}
	sb.WriteString("}\n\n")

	// ucumPrefixes
	sb.WriteString("// ucumPrefixes is the set of all UCUM metric SI prefixes plus\n")
	sb.WriteString("// binary (IEC) prefixes (Ki Mi Gi Ti ...) from ucum-essence.xml.\n")
	sb.WriteString("var ucumPrefixes = map[string]bool{\n")
	for _, p := range prefixes {
		fmt.Fprintf(&sb, "\t%q: true,\n", p)
	}
	sb.WriteString("}\n\n")

	// verboseToUCUM
	sb.WriteString("// verboseToUCUM maps lowercase English verbose unit words to their\n")
	sb.WriteString("// UCUM code suggestions. Used by suggestUCUM to provide helpful\n")
	sb.WriteString("// diagnostics when a unit like \"seconds\" is used instead of \"s\".\n")
	sb.WriteString("// Seeded from OTel's wordToUCUM table; not derived from the XML.\n")
	sb.WriteString("var verboseToUCUM = map[string]string{\n")
	for _, e := range verboseEntries {
		fmt.Fprintf(&sb, "\t%q: %q,\n", e.key, e.val)
	}
	sb.WriteString("}\n")

	if err := os.WriteFile(outPath, []byte(sb.String()), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genucum: cannot write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("genucum: wrote %s (%d atoms, %d prefixes, %d verbose entries)\n",
		outPath, len(atomSet), len(prefixSet), len(verboseEntries))
}

func sortedKeys(m map[string]bool) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
